# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce67f6e79198dc82f31a09717c95c7b2e07a43f6a2132d7180c2fb7639a4d604a7d6eed0d0e9e8db5ad05f67bd8a021e6bf115a66efc5071ef5c2a1e7157f8a1

test:
  secret_key_base: 02ca769c601b3439466d9f45eb3d0d98004debb3d7d58c685d361540e377e4d9c80235ccad2b2080339eeea5235368615a0b59abf0e30f051abf7203bc25dcd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
